"""
src/core/dtos/pdf_dtos.py
Data Transfer Objects (DTOs) for PDF document processing.

ARCHITECTURE NOTE:
These DTOs are immutable data containers that cross the boundary between the
PDF infrastructure layer (PyMuPDF adapter) and the application/service layer.
They must NOT contain SQLAlchemy models, repository references, or database IDs.

drawing_number vs file_name:
    file_name       = the bare OS filename, e.g. "UCC-E-101_RevA.pdf"
    drawing_number  = the human-readable engineering drawing identifier,
                      e.g. "UCC-E-101". Extracted from PDF metadata "Subject"
                      field when present, otherwise derived from the filename
                      stem (extension stripped, trailing revision suffix removed).
                      May be empty string if no reliable value can be determined.

creation_date / modification_date:
    Sourced from the PDF file's own metadata (XMP or Info dict).
    Both are optional strings in ISO-8601 format ("YYYY-MM-DD HH:MM:SS") or
    None when the PDF does not contain the field.
    Do NOT substitute the file-system mtime when PDF metadata is absent.
"""

from dataclasses import dataclass, field
from typing import List, Optional
from pathlib import Path


@dataclass(frozen=True)
class PageMetadataDTO:
    """Immutable metadata for a single PDF page."""
    page_number: int            # 1-indexed page number
    width_pt: float             # Page width in points (72 pt = 1 inch)
    height_pt: float            # Page height in points
    aspect_ratio: float
    has_native_text: bool       # True if page contains native searchable text layer
    text_character_count: int   # Number of native characters detected
    orientation_deg: int        # Rotation angle (0, 90, 180, 270)


@dataclass(frozen=True)
class PDFDocumentDTO:
    """
    Immutable metadata for an entire PDF engineering drawing file.

    Fields
    ------
    file_path       : Absolute path to the PDF file.
    file_name       : Bare filename including extension, e.g. "UCC-E-101.pdf".
    file_size_bytes : File size in bytes.
    file_hash_sha256: SHA-256 hex digest for duplicate detection.
    total_pages     : Total page count.
    is_encrypted    : True if the PDF is password-protected.
    is_scanned      : True when the majority of pages lack native text.
    title           : PDF "Title" metadata field, or None.
    author          : PDF "Author" metadata field, or None.
    drawing_number  : Engineering drawing identifier (e.g. "UCC-E-101").
                      Derived from PDF "Subject" field when present, otherwise
                      from the filename stem. Empty string if undetermined.
    creation_date   : PDF "CreationDate" as "YYYY-MM-DD HH:MM:SS", or None.
    modification_date: PDF "ModDate" as "YYYY-MM-DD HH:MM:SS", or None.
    pages           : Per-page metadata list.

    INTEGRATION WARNING:
    drawing_number is NOT the database DrawingModel.id ("DWG-XXXXXXXX").
    Never pass drawing_number as a foreign-key drawing_id to any repository.
    The database drawing_id is generated by DrawingRepository and returned
    after persisting this DTO.
    """
    file_path: Path
    file_name: str
    file_size_bytes: int
    file_hash_sha256: str
    total_pages: int
    is_encrypted: bool
    is_scanned: bool
    title: Optional[str] = None
    author: Optional[str] = None
    drawing_number: str = ""
    creation_date: Optional[str] = None
    modification_date: Optional[str] = None
    pages: List[PageMetadataDTO] = field(default_factory=list)


@dataclass(frozen=True)
class RenderedPageDTO:
    """Container holding a rendered page image buffer and display parameters."""
    page_number: int
    width_px: int
    height_px: int
    dpi: int
    image_bytes: bytes          # Raw PNG or JPEG byte stream
    format: str = "PNG"
